### PR TITLE
Minimal flask server that echos "Hello World" 

### PR DESCRIPTION
**Pull request by senongtor**
#9 create a flask server that run on port 8888 and echo "Hello world"

### CODE REVIEW

**Comment by WesPainter** [comment]
Need to set an environment variable for flask to run using `flask run`. Consider dropping a line in the vagrant file to add an environment variable for FLASK_APP.  Need an alternative for writing the folloing line each time we spin up a virtual machine:

`export FLASK_APP=/vagrant/shopcart.py`

**Comment by senongtor** [comment]
@WesPainter By reading this page [http://flask.pocoo.org/docs/0.12/quickstart/](url)
it seems like that `flask run` will always run on port 5000. Also if you want to use that command, you need to do `flask run --host=0.0.0.0` to make the page public to the host.

However I did find a solution to export that path: 
`echo "export FLASK_APP=/vagrant/shopcart.py" >> /home/vagrant/.bashrc`

I think either we need to change the port we use to 5000 or change how we run the server to 
`python /vagrant/shopcart.py`

**Comment by WesPainter** [comment]
@senongtor You can use arguments to change the port just like the host `flask run --port=8888`, but this still doesn't improve on the length of the command to start it.  The quickstart guide however doesn't mention running the server by invoking the server application file directly with python like you mention, so we either live with always specifying the host and port when we invoke flask run or else change to port 5000 and still have to deal with specifying the host as 0.0.0.0. Your call.

**Comment by senongtor** [comment]
@WesPainter Nice! I will stick to port 8888 so that we don't have to rename all the issues

**Comment by WesPainter** [comment]
@senongtor 
Another thought might be to add an alias to bash_aliases that can replace flask run altogether that we can use internally to make our own lives easier. Something like:

`echo "alias start_flask='flask run --host=0.0.0.0 --port=8888" > ~\.bash_aliases`

Also this helps us keep host and port config in the vagrant file.

**Comment by senongtor** [comment]
@WesPainter Please review the change

**Comment by WesPainter** [comment]
Awesome! So easy to start. Thanks man.

**Pull request merged**
